# Generated by Django 4.0.3 on 2022-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_billing_remain_due_alter_billing_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='annual_rate',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='months',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Installment Pay', 'Installment Pay'), ('Full Pay', 'Full Pay')], max_length=200, null=True),
        ),
    ]
