# Generated by Django 4.0.3 on 2022-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_order_annual_rate_order_months_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
